### ISSUE TITLE
Can't override input style

### ISSUE THREAD

**Issue by kentforth** [ikloster03/vue-dadata#106]
I added my own class, but can't style input. 
**What I did wrong?**

```
<vue-dadata
          v-model="form.city"
          classes="address-component"
          token=123"
        />

.address-component {
  input {
    border: 2px solid green !important;
  }
}
```

![1](https://user-images.githubusercontent.com/17134421/116818579-584fc900-ab96-11eb-99e3-dc1360956814.jpg)

**Comment by ikloster03** [comment]
@kentforth I'm sorry for waiting! Have you already decided your problem?
You can use defaultClass
