### ISSUE TITLE
Module parse failed: Unexpected token (26:29297)  

### ISSUE THREAD

**Issue by archieDeveloper** [ikloster03/vue-dadata#125]
**Describe the bug**
Error building Nuxt project. 

ERROR  Failed to compile with 1 errors
ERROR  in ./node_modules/vue-dadata/dist/vuedadatacomponent.min.js

Module parse failed: Unexpected token (26:29297)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**To Reproduce**
1. terminal `npm install vue-dadata --save`
2. page component `import VueDadata from 'vue-dadata';` and use the component in the template
3. terminal `npm run dev`

**Expected behavior**
Everything works.

**Env**
 - nuxt v2.15.8
 - npm 7.20.5
 - node v14.15.1
 - vue-dadata 1.4.11

**Comment by ikloster03** [comment]
@archieDeveloper I've fixed this bug #126
