### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by archieDeveloper** [ikloster03/vue-dadata#127]
**Is your feature request related to a problem? Please describe.**
Input field does not support server side rendering.

**Describe the solution you'd like**
Server side should render html form wireframe without throwing document is not defined error.

**Additional context**
Using nuxtjs with ssr.

**Comment by ikloster03** [comment]
@archieDeveloper could you show a code example with the problem?

**Comment by archieDeveloper** [comment]
@ikloster03 https://codesandbox.io/s/nuxt-vue-dadata-i332t

Sorry, it seems there are no problems, you can close the issue.
