### ISSUE TITLE
Vite build and es.js files

### ISSUE THREAD

**Issue by new-user-name** [ikloster03/vue-dadata#146]
Hi, I don't know is this a bug or I miss something. You have
`"import": "./dist/vue-dadata.es.js",`
in `package. json`. But vue build gives only js, umd.js and cjs files with the settings
`formats: ['es', 'umd', 'cjs']`

So I receive
 `Failed to resolve entry for package "vue-dadata". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]`

**Comment by ikloster03** [comment]
@new-user-name thank you for feedbak! Fixed.
