### ISSUE TITLE
onChange problem

### ISSUE THREAD

**Issue by gelid** [ikloster03/vue-dadata#44]
hi, I'm using your solution in my project.
Here's the code call
```
<vue-dadata token="my_api_key"
             placeholder="Work address"
              inputName="address"
             onChange="setAddress"
></vue-dadata>
```
in component methods block im write
```
setAddress: function(data) {
      console.log(data)
},
```

but in console im get error 
```
app.js:40739 Uncaught (in promise) TypeError: this.onChange is not a function
    at a.selectSuggestion (app.js:40739)
```

what am I doing wrong?
I didn't find any examples of using the method correctly

**Comment by dbapril** [comment]
Присоединяюсь, дайте какой-нибудь пример использования, полдня убил на этот метод и ноль результатов.

**Comment by ikloster03** [comment]
Hello @gelid and @dbapril !
I've added the [onChange example](https://github.com/ikloster03/vue-dadata/pull/45/files) 
@gelid, for your code:
```
<vue-dadata 
   token="my_api_key"
   placeholder="Work address"
   inputName="address"
   :onChange="setAddress"
></vue-dadata>
```
You should use [v-bind directive](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand).
And you can more read [here](https://vuejs.org/v2/api/#v-bind).
