### ISSUE TITLE
yarn add vue-dadata problem

### ISSUE THREAD

**Issue by cavidz** [ikloster03/vue-dadata#46]
Hello everybody!

I have an installation problem with yarn in my VueJs project. After 
`yarn add vue-dadata`
seems it has been installed. But when I want to initialize global or local it gives me an error:

**This dependency was not found:**

* vue-dadata in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--18-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Auth/Signup.vue?vue&type=script&lang=js&

**To install it, you can run: npm install --save vue-dadata**

In my case I have to install it by yarn and npm is not preferred way. Is there any mistake by my side?

**Comment by ikloster03** [comment]
@cavidz, thank you!
I've found a problem and fixed it.
I forgot to build a dist folder for npm publish.

**Comment by cavidz** [comment]
Thank you for quick reaction! =)
