### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier (Chrome ver. 49)

### ISSUE THREAD

**Issue by dbapril** [ikloster03/vue-dadata#67]
Hello again guys! 
Have some problems with browsers compatibility. Google Chrome (49 ver.) can not parse a code and throws out an error. Possible that this problem is related with comments. When I turn of dadata-vue from my code, the app builds successfully and displays in browser. Tested this situation in Windows XP and Ubuntu 20.04, have this error in both OS.  Seems that same problem there is in IE, but i didn't test it myself yet (but my collegues saw similar signs in MS browsers older than Edge).
I'm appending a screenshot of devtools and hope for your help. 
Happy holiday!

![screen](https://user-images.githubusercontent.com/48928659/84385794-df035c80-abf8-11ea-82dc-b2d32f38db6e.jpg)

**Comment by ikloster03** [comment]
Hello, @dbapril!
Thank you for the bug report!
We'll consider this bug, as we'll know something, we'll inform you immediately.
Happy holiday too!

**Comment by dbapril** [comment]
Hi everyone! I found out the reason of this error. The plugin is written on ES6, but the others plugins in node_modules of my project provide ES5 stadart. Adding of a few lines of code in my vue.config.js solved this problem (thanks for authors of vuetify documentation for this example). So add this code and your app will work in old browsers: 
`module.exports = {
  transpileDependencies:[/node_modules[/\\\\]vue-dadata[/\\\\]/]
}`
It will well if this configuration feature will added in documentation of this plugin.
And this is how it looks on screenshot. 
![screen2](https://user-images.githubusercontent.com/48928659/84572911-f16ec900-ada5-11ea-9d5b-a64f620eddcd.jpg)
