### ISSUE TITLE
onChange doesn't fire on mouse click 

### ISSUE THREAD

**Issue by alexeyklenov** [ikloster03/vue-dadata#73]
Hello!
onChange function doesn't fire on mouse click. As I can see, this logic was broken by commit a1670d414001bf7ee5ca48e23cfe0208c521e308 (fix and optimize request).
![image](https://user-images.githubusercontent.com/16133317/84981212-6e56c580-b14d-11ea-93ea-ebac66afc202.png)

**Comment by ikloster03** [comment]
@alexeyklenov, thank you!
@Roshett, please, fix it.

**Comment by RayVector** [comment]
A similar problem, very dangerous and it ruined the plugin. Please fix.

Event onChange doesn't work.
`@onChange`

**Comment by ikloster03** [comment]
Hello, @alexeyklenov, @RayVector, @Roshett! I've fixed this bug in release v1.4.7. Would you check it, please?
