### ISSUE TITLE
Not all data recieve

### ISSUE THREAD

**Issue by gelid** [ikloster03/vue-dadata#75]
hi
I'm using the latest version (with a bug on the onChange event). 
Also, after updating it, not all the data in the response began to arrive.
For example, federal_district is always null. 
Example of the address of **Тульская обл, г Тула, пр-кт Ленина, д 85**. The site returns both the city district and the Federal district. And this module returns null.

**Comment by alexeyklenov** [comment]
Hi! That's because enriched data is not loaded after suggestion selected. This logic is described on https://confluence.hflabs.ru/pages/viewpage.action?pageId=980812161. It is neccessary to make request with count = 1 after user selection. I can suggest pull request with a solution to this problem.

**Comment by ikloster03** [comment]
Hello, @gelid. I've fixed onChange's bug at issue #73.
@alexeyklenov, thank you for your answer!

**Comment by gelid** [comment]
Hello @ikloster03 After the update, the event worked, but there is still no data.
last 2 quert to https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address
{query: "г Тула, пр-кт Ленина, д 85", count: 10, to_bound: {}, from_bound: {}, language: "ru",…}
and last is empty
no query with count 1

**Comment by alexeyklenov** [comment]
Hello, I've made pull request with solution to this problem.

**Comment by alexeyklenov** [comment]
Hi, @gelid.  Not all data problem was fixed in [https://github.com/ikloster03/vue-dadata/pull/80](url)

**Comment by gelid** [comment]
hi, @alexeyklenov 

im use 
npm update
npm update vue-dadata
npm update vue-dadata - f
remove folder node_modules/vue-dadata and run npm i 
nothing change 

manualy update 2 files from commit not working too..

**Comment by ikloster03** [comment]
@gelid, I got it, thank you for your feedback. It's my fault. I forgot to create a release. But now I fix it.

**Comment by gelid** [comment]
@ikloster03 , thank you! now it work perfect
