### ISSUE TITLE
ie 11 not working arrow function

### ISSUE THREAD

**Issue by gelid** [ikloster03/vue-dadata#84]
**Describe the bug**
in ie 11 not working arrow function
`Ro({type:Object,default:()=>({language:"ru",locations:[],locationsBoost:[]})})]`

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Internet Explorer
 - Version  11

**Additional context**
Im using Laravel mix + vue dadata. 
all my arrow function on build transform to ES5
but imported script has own arrow function.

can u build in to es5?

**Comment by ikloster03** [comment]
@gelid do you have a babel for your build?

**Comment by gelid** [comment]
sorry, but im dont know, im backend developer.. it is default laravel mix setup. 
in package.json babel exist  "@babel/preset-env": "^7.11.0",

and i think if i dont have babel my own arrow function not be transformed

**Comment by gelid** [comment]
solved
https://github.com/JeffreyWay/laravel-mix/issues/2174#issuecomment-569929210
