### ISSUE TITLE
Было бы идеально указаывать URL

### ISSUE THREAD

**Issue by ArcheeNic** [ikloster03/vue-dadata#92]
Хотел подключить плагин ,потому что у меня и адреса и стандартизация ФИО.
Но, как оказалось работает этот плагин только с адресами.
Было бы прекрасно, если бы как и в getSuggestions.ts в сам компонент <vue-dadata> можно было передавать URL запроса или указать тип запрашиваемых данных

**Comment by akrylo27** [comment]
props url работает!
