### ISSUE TITLE
Bug on android

### ISSUE THREAD

**Issue by savayer** [ikloster03/vue-dadata#94]
**Bug description**
I'm entering the first letter (or several) of a city, selecting it and after that the value does not appear in the input.
You have to enter the city completely and only after that the select works

**Screenshots**
I check this in BrowserStack. I entered the first letters, chose the proposed city, got the coordinates, but the value that I entered remained in the input field

![2020-11-19_15-49](https://user-images.githubusercontent.com/19423784/99674562-2d266100-2ab1-11eb-8b2c-38fbd00989ce.png)

**Smartphone:**
 - Device: Xiaomi Redmi, Motorolla G7 Play, Google Pixel 4
 - OS: Android
 - Browser Chrome, Firefox
 - Version last

Do you have any ideas?
Thanks

**Comment by allinchow** [comment]
also have this bug on Android

**Comment by allinchow** [comment]
while the bug is not fixed - added a small dirty fix, it works for me: 
```
getDataByCity(event) { // VueDadata prop :onChange="getDataByCity"
    
    //.... manipulations with event 

    // small fix

    document.querySelector('.vue-dadata__input').value = event.value;
    
} 
```

**Comment by savayer** [comment]
@allinchow Thanks
